title: YafaiOS Notes
description: Swift + UIKit notes, tips, and patterns.
theme: minima
sass:
  style: compressed

# Optional but helpful
markdown: kramdown
permalink: pretty

header_pages:
  - swift.md
  - uikit.md
  - redirects/oauth.md
